version: '3.4'

services:
  python:
    build:
      context: ./
      args:
        - "MS_UID=${MS_UID}"
        - "PROXY=${HTTP_PROXY}"
    environment:
    - http_proxy=${HTTP_PROXY}
    - https_proxy=${HTTP_PROXY}
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTP_PROXY}
    restart: always
    volumes:
    - ./src:/work
    command: ["tail", "-f", "/dev/null"]
