"""
check_error_response.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CheckErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phase: int=None, terms: List[str]=None, reason: int=None):  # noqa: E501
        """CheckErrorResponse - a model defined in Swagger

        :param phase: The phase of this CheckErrorResponse.  # noqa: E501
        :type phase: int
        :param terms: The terms of this CheckErrorResponse.  # noqa: E501
        :type terms: List[str]
        :param reason: The reason of this CheckErrorResponse.  # noqa: E501
        :type reason: int
        """
        self.swagger_types = {
            'phase': int,
            'terms': List[str],
            'reason': int
        }

        self.attribute_map = {
            'phase': 'phase',
            'terms': 'terms',
            'reason': 'reason'
        }
        self._phase = phase
        self._terms = terms
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'CheckErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckErrorResponse of this CheckErrorResponse.  # noqa: E501
        :rtype: CheckErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phase(self) -> int:
        """Gets the phase of this CheckErrorResponse.


        :return: The phase of this CheckErrorResponse.
        :rtype: int
        """
        return self._phase

    @phase.setter
    def phase(self, phase: int):
        """Sets the phase of this CheckErrorResponse.


        :param phase: The phase of this CheckErrorResponse.
        :type phase: int
        """

        self._phase = phase

    @property
    def terms(self) -> List[str]:
        """Gets the terms of this CheckErrorResponse.


        :return: The terms of this CheckErrorResponse.
        :rtype: List[str]
        """
        return self._terms

    @terms.setter
    def terms(self, terms: List[str]):
        """Sets the terms of this CheckErrorResponse.


        :param terms: The terms of this CheckErrorResponse.
        :type terms: List[str]
        """

        self._terms = terms

    @property
    def reason(self) -> int:
        """Gets the reason of this CheckErrorResponse.


        :return: The reason of this CheckErrorResponse.
        :rtype: int
        """
        return self._reason

    @reason.setter
    def reason(self, reason: int):
        """Sets the reason of this CheckErrorResponse.


        :param reason: The reason of this CheckErrorResponse.
        :type reason: int
        """

        self._reason = reason
