"""
check_error_response.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CheckErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phase: int=None, terms: List[str]=None, langs: List[str]=None, reason: int=None, file_type: int=None):  # noqa: E501
        """CheckErrorResponse - a model defined in Swagger

        :param phase: The phase of this CheckErrorResponse.  # noqa: E501
        :type phase: int
        :param terms: The terms of this CheckErrorResponse.  # noqa: E501
        :type terms: List[str]
        :param langs: The langs of this CheckErrorResponse.  # noqa: E501
        :type langs: List[str]
        :param reason: The reason of this CheckErrorResponse.  # noqa: E501
        :type reason: int
        :param file_type: The file_type of this CheckErrorResponse.  # noqa: E501
        :type file_type: int

        """
        self.swagger_types = {
            'phase': int,
            'terms': List[str],
            'langs': List[str],
            'reason': int,
            'file_type': int
        }

        self.attribute_map = {
            'phase': 'phase',
            'terms': 'terms',
            'langs': 'langs',
            'reason': 'reason',
            'file_type': 'file_type'
        }
        self._phase = phase
        self._terms = terms
        self._langs = langs
        self._reason = reason
        self._file_type = file_type

    @classmethod
    def from_dict(cls, dikt) -> 'CheckErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckErrorResponse of this CheckErrorResponse.  # noqa: E501
        :rtype: CheckErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phase(self) -> int:
        """Gets the phase of this CheckErrorResponse.


        :return: The phase of this CheckErrorResponse.
        :rtype: int
        """
        return self._phase

    @phase.setter
    def phase(self, phase: int):
        """Sets the phase of this CheckErrorResponse.


        :param phase: The phase of this CheckErrorResponse.
        :type phase: int
        """

        self._phase = phase

    @property
    def terms(self) -> List[str]:
        """Gets the terms of this CheckErrorResponse.


        :return: The terms of this CheckErrorResponse.
        :rtype: List[str]
        """
        return self._terms

    @terms.setter
    def terms(self, terms: List[str]):
        """Sets the terms of this CheckErrorResponse.


        :param terms: The terms of this CheckErrorResponse.
        :type terms: List[str]
        """

        self._terms = terms

    @property
    def langs(self) -> List[str]:
        """Gets the langs of this CheckErrorResponse.


        :return: The langs of this CheckErrorResponse.
        :rtype: List[str]
        """
        return self._langs

    @langs.setter
    def langs(self, langs: List[str]):
        """Sets the langs of this CheckErrorResponse.


        :param langs: The langs of this CheckErrorResponse.
        :type langs: List[str]
        """

        self._langs = langs

    @property
    def reason(self) -> int:
        """Gets the reason of this CheckErrorResponse.


        :return: The reason of this CheckErrorResponse.
        :rtype: int
        """
        return self._reason

    @reason.setter
    def reason(self, reason: int):
        """Sets the reason of this CheckErrorResponse.


        :param reason: The reason of this CheckErrorResponse.
        :type reason: int
        """

        self._reason = reason

    @property
    def file_type(self) -> int:
        """Gets the file_type of this CheckErrorResponse.


        :return: The file_type of this CheckErrorResponse.
        :rtype: int
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type: int):
        """Sets the file_type of this CheckErrorResponse.


        :param file_type: The file_type of this CheckErrorResponse.
        :type file_type: int
        """

        self._file_type = file_type