"""
error_response.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result: int=None, message: str=None):  # noqa: E501
        """ErrorResponse - a model defined in Swagger

        :param result: The result of this ErrorResponse.  # noqa: E501
        :type result: int
        :param message: The message of this ErrorResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'result': int,
            'message': str
        }

        self.attribute_map = {
            'result': 'result',
            'message': 'message'
        }
        self._result = result
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> int:
        """Gets the result of this ErrorResponse.


        :return: The result of this ErrorResponse.
        :rtype: int
        """
        return self._result

    @result.setter
    def result(self, result: int):
        """Sets the result of this ErrorResponse.


        :param result: The result of this ErrorResponse.
        :type result: int
        """

        self._result = result

    @property
    def message(self) -> str:
        """Gets the message of this ErrorResponse.


        :return: The message of this ErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorResponse.


        :param message: The message of this ErrorResponse.
        :type message: str
        """

        self._message = message
