"""
example_phrases.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExamplePhrases(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, phrase: str=None):  # noqa: E501
        """ExamplePhrases - a model defined in Swagger

        :param id: The id of this ExamplePhrases.  # noqa: E501
        :type id: int
        :param phrase: The phrase of this ExamplePhrases.  # noqa: E501
        :type phrase: str
        """
        self.swagger_types = {
            'id': int,
            'phrase': str
        }

        self.attribute_map = {
            'id': 'id',
            'phrase': 'phrase'
        }
        self._id = id
        self._phrase = phrase

    @classmethod
    def from_dict(cls, dikt) -> 'ExamplePhrases':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExamplePhrases of this ExamplePhrases.  # noqa: E501
        :rtype: ExamplePhrases
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ExamplePhrases.


        :return: The id of this ExamplePhrases.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ExamplePhrases.


        :param id: The id of this ExamplePhrases.
        :type id: int
        """

        self._id = id

    @property
    def phrase(self) -> str:
        """Gets the phrase of this ExamplePhrases.


        :return: The phrase of this ExamplePhrases.
        :rtype: str
        """
        return self._phrase

    @phrase.setter
    def phrase(self, phrase: str):
        """Sets the phrase of this ExamplePhrases.


        :param phrase: The phrase of this ExamplePhrases.
        :type phrase: str
        """

        self._phrase = phrase
