"""
get_all_success_response.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.editing_vocabulary import EditingVocabulary  # noqa: F401,E501
from swagger_server.models.reference_vocabulary import ReferenceVocabulary  # noqa: F401,E501
from swagger_server import util


class GetAllSuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, editing_vocabulary: List[EditingVocabulary]=None, reference_vocabulary: List[ReferenceVocabulary]=None):  # noqa: E501
        """GetAllSuccessResponse - a model defined in Swagger

        :param editing_vocabulary: The editing_vocabulary of this GetAllSuccessResponse.  # noqa: E501
        :type editing_vocabulary: List[EditingVocabulary]
        :param reference_vocabulary: The reference_vocabulary of this GetAllSuccessResponse.  # noqa: E501
        :type reference_vocabulary: List[ReferenceVocabulary]
        """
        self.swagger_types = {
            'editing_vocabulary': List[EditingVocabulary],
            'reference_vocabulary': List[ReferenceVocabulary]
        }

        self.attribute_map = {
            'editing_vocabulary': 'EditingVocabulary',
            'reference_vocabulary': 'ReferenceVocabulary'
        }
        self._editing_vocabulary = editing_vocabulary
        self._reference_vocabulary = reference_vocabulary

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllSuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAllSuccessResponse of this GetAllSuccessResponse.  # noqa: E501
        :rtype: GetAllSuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def editing_vocabulary(self) -> List[EditingVocabulary]:
        """Gets the editing_vocabulary of this GetAllSuccessResponse.


        :return: The editing_vocabulary of this GetAllSuccessResponse.
        :rtype: List[EditingVocabulary]
        """
        return self._editing_vocabulary

    @editing_vocabulary.setter
    def editing_vocabulary(self, editing_vocabulary: List[EditingVocabulary]):
        """Sets the editing_vocabulary of this GetAllSuccessResponse.


        :param editing_vocabulary: The editing_vocabulary of this GetAllSuccessResponse.
        :type editing_vocabulary: List[EditingVocabulary]
        """

        self._editing_vocabulary = editing_vocabulary

    @property
    def reference_vocabulary(self) -> List[ReferenceVocabulary]:
        """Gets the reference_vocabulary of this GetAllSuccessResponse.


        :return: The reference_vocabulary of this GetAllSuccessResponse.
        :rtype: List[ReferenceVocabulary]
        """
        return self._reference_vocabulary

    @reference_vocabulary.setter
    def reference_vocabulary(self, reference_vocabulary: List[ReferenceVocabulary]):
        """Sets the reference_vocabulary of this GetAllSuccessResponse.


        :param reference_vocabulary: The reference_vocabulary of this GetAllSuccessResponse.
        :type reference_vocabulary: List[ReferenceVocabulary]
        """

        self._reference_vocabulary = reference_vocabulary
