"""
search_success_response.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.example_phrases import ExamplePhrases  # noqa: F401,E501
from swagger_server import util


class SearchSuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, all_result_count: int=None, example_phrases: List[ExamplePhrases]=None):  # noqa: E501
        """SearchSuccessResponse - a model defined in Swagger

        :param all_result_count: The all_result_count of this SearchSuccessResponse.  # noqa: E501
        :type all_result_count: int
        :param example_phrases: The example_phrases of this SearchSuccessResponse.  # noqa: E501
        :type example_phrases: List[ExamplePhrases]
        """
        self.swagger_types = {
            'all_result_count': int,
            'example_phrases': List[ExamplePhrases]
        }

        self.attribute_map = {
            'all_result_count': 'AllResultCount',
            'example_phrases': 'ExamplePhrases'
        }
        self._all_result_count = all_result_count
        self._example_phrases = example_phrases

    @classmethod
    def from_dict(cls, dikt) -> 'SearchSuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchSuccessResponse of this SearchSuccessResponse.  # noqa: E501
        :rtype: SearchSuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def all_result_count(self) -> int:
        """Gets the all_result_count of this SearchSuccessResponse.

        Number of search results  # noqa: E501

        :return: The all_result_count of this SearchSuccessResponse.
        :rtype: int
        """
        return self._all_result_count

    @all_result_count.setter
    def all_result_count(self, all_result_count: int):
        """Sets the all_result_count of this SearchSuccessResponse.

        Number of search results  # noqa: E501

        :param all_result_count: The all_result_count of this SearchSuccessResponse.
        :type all_result_count: int
        """

        self._all_result_count = all_result_count

    @property
    def example_phrases(self) -> List[ExamplePhrases]:
        """Gets the example_phrases of this SearchSuccessResponse.

        Search results data(MAX100)  # noqa: E501

        :return: The example_phrases of this SearchSuccessResponse.
        :rtype: List[ExamplePhrases]
        """
        return self._example_phrases

    @example_phrases.setter
    def example_phrases(self, example_phrases: List[ExamplePhrases]):
        """Sets the example_phrases of this SearchSuccessResponse.

        Search results data(MAX100)  # noqa: E501

        :param example_phrases: The example_phrases of this SearchSuccessResponse.
        :type example_phrases: List[ExamplePhrases]
        """

        self._example_phrases = example_phrases
