"""
upload.py COPYRIGHT FUJITSU LIMITED 2021
"""
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Upload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, editing_vocabulary: str=None, reference_vocabulary1: str=None, reference_vocabulary2: str=None, reference_vocabulary3: str=None, example_phrases: str=None):  # noqa: E501
        """Upload - a model defined in Swagger

        :param editing_vocabulary: The editing_vocabulary of this Upload.  # noqa: E501
        :type editing_vocabulary: str
        :param reference_vocabulary1: The reference_vocabulary1 of this Upload.  # noqa: E501
        :type reference_vocabulary1: str
        :param reference_vocabulary2: The reference_vocabulary2 of this Upload.  # noqa: E501
        :type reference_vocabulary2: str
        :param reference_vocabulary3: The reference_vocabulary3 of this Upload.  # noqa: E501
        :type reference_vocabulary3: str
        :param example_phrases: The example_phrases of this Upload.  # noqa: E501
        :type example_phrases: str
        """
        self.swagger_types = {
            'editing_vocabulary': str,
            'reference_vocabulary1': str,
            'reference_vocabulary2': str,
            'reference_vocabulary3': str,
            'example_phrases': str
        }

        self.attribute_map = {
            'editing_vocabulary': 'editing_vocabulary',
            'reference_vocabulary1': 'reference_vocabulary1',
            'reference_vocabulary2': 'reference_vocabulary2',
            'reference_vocabulary3': 'reference_vocabulary3',
            'example_phrases': 'example_phrases'
        }
        self._editing_vocabulary = editing_vocabulary
        self._reference_vocabulary1 = reference_vocabulary1
        self._reference_vocabulary2 = reference_vocabulary2
        self._reference_vocabulary3 = reference_vocabulary3
        self._example_phrases = example_phrases

    @classmethod
    def from_dict(cls, dikt) -> 'Upload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Upload of this Upload.  # noqa: E501
        :rtype: Upload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def editing_vocabulary(self) -> str:
        """Gets the editing_vocabulary of this Upload.

        editing_vocabulary is xlsx file  # noqa: E501

        :return: The editing_vocabulary of this Upload.
        :rtype: str
        """
        return self._editing_vocabulary

    @editing_vocabulary.setter
    def editing_vocabulary(self, editing_vocabulary: str):
        """Sets the editing_vocabulary of this Upload.

        editing_vocabulary is xlsx file  # noqa: E501

        :param editing_vocabulary: The editing_vocabulary of this Upload.
        :type editing_vocabulary: str
        """

        self._editing_vocabulary = editing_vocabulary

    @property
    def reference_vocabulary1(self) -> str:
        """Gets the reference_vocabulary1 of this Upload.

        reference_vocabulary1 is xlsx file  # noqa: E501

        :return: The reference_vocabulary1 of this Upload.
        :rtype: str
        """
        return self._reference_vocabulary1

    @reference_vocabulary1.setter
    def reference_vocabulary1(self, reference_vocabulary1: str):
        """Sets the reference_vocabulary1 of this Upload.

        reference_vocabulary1 is xlsx file  # noqa: E501

        :param reference_vocabulary1: The reference_vocabulary1 of this Upload.
        :type reference_vocabulary1: str
        """

        self._reference_vocabulary1 = reference_vocabulary1

    @property
    def reference_vocabulary2(self) -> str:
        """Gets the reference_vocabulary2 of this Upload.

        reference_vocabulary2 is xlsx file  # noqa: E501

        :return: The reference_vocabulary2 of this Upload.
        :rtype: str
        """
        return self._reference_vocabulary2

    @reference_vocabulary2.setter
    def reference_vocabulary2(self, reference_vocabulary2: str):
        """Sets the reference_vocabulary2 of this Upload.

        reference_vocabulary2 is xlsx file  # noqa: E501

        :param reference_vocabulary2: The reference_vocabulary2 of this Upload.
        :type reference_vocabulary2: str
        """

        self._reference_vocabulary2 = reference_vocabulary2

    @property
    def reference_vocabulary3(self) -> str:
        """Gets the reference_vocabulary3 of this Upload.

        reference_vocabulary3 is xlsx file  # noqa: E501

        :return: The reference_vocabulary3 of this Upload.
        :rtype: str
        """
        return self._reference_vocabulary3

    @reference_vocabulary3.setter
    def reference_vocabulary3(self, reference_vocabulary3: str):
        """Sets the reference_vocabulary3 of this Upload.

        reference_vocabulary3 is xlsx file  # noqa: E501

        :param reference_vocabulary3: The reference_vocabulary3 of this Upload.
        :type reference_vocabulary3: str
        """

        self._reference_vocabulary3 = reference_vocabulary3

    @property
    def example_phrases(self) -> str:
        """Gets the example_phrases of this Upload.

        example_phrases is txt file  # noqa: E501

        :return: The example_phrases of this Upload.
        :rtype: str
        """
        return self._example_phrases

    @example_phrases.setter
    def example_phrases(self, example_phrases: str):
        """Sets the example_phrases of this Upload.

        example_phrases is txt file  # noqa: E501

        :param example_phrases: The example_phrases of this Upload.
        :type example_phrases: str
        """

        self._example_phrases = example_phrases
